Be more explicit about build dependencies
Chia-Network/chiapos pull request #215
Opened 2021-04-24 05:22 UTC by aqk

Update dependency docs

2021-04-24 12:30 UTC, robertmetcalf approved these changes
Looks good to me

2021-04-24 15:25 UTC, hoffmang9 requested changes

2021-04-24 15:25 UTC, hoffmang9 commented on README.md
> +sudo apt install libpython3.8-dev cmake
I'm not sure it is *3.8* on all of the Distros. We've been just doing libpython3-dev for cross compatibility and it's been working.

2021-06-16 03:16 UTC, mikehaas763 approved these changes

2024-10-31 16:53 UTC, closed without merging